//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleHoras.DATA.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteIp
    {
        public int ClienteIpID { get; set; }
        public int ClienteID { get; set; }
        public string Ip { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
