//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleHoras.DATA.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.Alocacao = new HashSet<Alocacao>();
            this.Lancamento = new HashSet<Lancamento>();
            this.HorasExtras = new HashSet<HorasExtras>();
        }
    
        public int ContratoID { get; set; }
        public int ClienteID { get; set; }
        public string NumeroReferencia { get; set; }
        public string ModalidadeContrato { get; set; }
        public string ModalidadeApuracao { get; set; }
        public Nullable<int> QtdHorasMes { get; set; }
        public bool ApuracaoHoraExtra { get; set; }
        public Nullable<decimal> ValorHoraExtra { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
        public string Descricao { get; set; }
        public bool Ativo { get; set; }
        public Nullable<decimal> ValorHora { get; set; }
        public Nullable<System.TimeSpan> HorarioEntrada { get; set; }
        public Nullable<System.TimeSpan> HorarioSaida { get; set; }
        public Nullable<System.TimeSpan> IntervaloInicio { get; set; }
        public Nullable<System.TimeSpan> IntervaloFim { get; set; }
        public Nullable<bool> ValidarLocalizacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alocacao> Alocacao { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lancamento> Lancamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorasExtras> HorasExtras { get; set; }
    }
}
