//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleHoras.DATA.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorasExtras
    {
        public int AprovacaoID { get; set; }
        public int ProfissionalID { get; set; }
        public System.DateTime DataInicial { get; set; }
        public System.DateTime DataFinal { get; set; }
        public bool Pendente { get; set; }
        public int ContratoID { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Profissional Profissional { get; set; }
    }
}
