//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleHoras.DATA.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lancamento
    {
        public long LancamentoID { get; set; }
        public int ContratoID { get; set; }
        public int ProfissionalID { get; set; }
        public Nullable<System.DateTime> HorarioEntrada { get; set; }
        public Nullable<System.DateTime> HorarioSaida { get; set; }
        public string Atividade { get; set; }
        public Nullable<bool> LocalValidado { get; set; }
        public string Observacao { get; set; }
        public bool Pendente { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Profissional Profissional { get; set; }
    }
}
