//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleHoras.DATA.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UsuarioID { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> ProfissionalID { get; set; }
        public Nullable<bool> Adm { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Profissional Profissional { get; set; }
    }
}
